[package]
name = "touch"
version = "0.1.0"
edition = "2021"

[dependencies]
getopts = "0.2.21"

[dependencies.terminal_print]
path = "../../kernel/terminal_print"

[dependencies.task]
path = "../../kernel/task"

[dependencies.memfs]
path = "../../kernel/memfs"